### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JodhwaniMadhur** [bhattbhavesh91/cowin-vaccination-slot-availability#20]
**### Traceback (most recent call last):
  File "c:\users\intel\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\intel\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\INTEL\AppData\Local\Programs\Python\Python39\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\__init__.py", line 46, in <module>
    from streamlit import logger as _logger
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\logger.py", line 21, in <module>
    from streamlit import config
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\config.py", line 28, in <module>
    from streamlit import config_util
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\config_util.py", line 4, in <module>
    import click
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\click\__init__.py", line 7, in <module>
PS C:\Users\INTEL\Desktop\Coding\cowin-vaccination-slot-availability-main> streamlit run app.py
Traceback (most recent call last):
  File "c:\users\intel\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\intel\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\INTEL\AppData\Local\Programs\Python\Python39\Scripts\streamlit.exe\__main__.py", line 4, in <module>       
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\__init__.py", line 46, in <module>
    from streamlit import logger as _logger
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\logger.py", line 21, in <module>
    from streamlit import config
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\config.py", line 28, in <module>
    from streamlit import config_util
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\streamlit\config_util.py", line 4, in <module>
    import click
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\click\__init__.py", line 7, in <module>
    from .core import Argument
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 9, in <module>
    from ._compat import isidentifier
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\click\_compat.py", line 685, in <module>
    import colorama
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\colorama\__init__.py", line 2, in <module>
    from .initialise import init, deinit, reinit, colorama_text
ValueError: source code string cannot contain null bytes**

it shows all this as errors

**Comment by bhattbhavesh91** [comment]
I just ran the code and it works fine! 
This thread should help - https://github.com/jupyter/notebook/issues/3166

**Comment by JodhwaniMadhur** [comment]
Hey,I am pretty new to PYTHON and still can't understand the error,can you please explain it to me and help me solve it?It shows this now and I am unable to understand it from the link you had sent nor it is helping while I am running it in colab.

**Traceback (most recent call last):
  File "C:\Users\INTEL\AppData\Local\Programs\Python\Python39\Scripts\pip-script.py", line 33, in <module>
    sys.exit(load_entry_point('pip==21.1.1', 'console_scripts', 'pip')())
  File "C:\Users\INTEL\AppData\Local\Programs\Python\Python39\Scripts\pip-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\intel\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\intel\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\utils\misc.py", line 38, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 523, in <module>
    from pip._vendor.tenacity.tornadoweb import TornadoRetrying
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\tenacity\tornadoweb.py", line 23, in <module>
    from tornado import gen
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 81, in <module>
    from tornado.concurrent import (
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\tornado\concurrent.py", line 34, in <module>
    from tornado.log import app_log
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\tornado\log.py", line 38, in <module>
    import colorama  # type: ignore
  File "c:\users\intel\appdata\local\programs\python\python39\lib\site-packages\colorama\__init__.py", line 2, in <module>
    from .initialise import init,deinit,reinit,colorama_text
ValueError: source code string cannot contain null bytes**
