### ISSUE TITLE
streamlit is sowing error

### ISSUE THREAD

**Issue by aarkay016** [bhattbhavesh91/cowin-vaccination-slot-availability#26]
_Traceback (most recent call last):
  File "c:\users\rishu\appdata\local\programs\python\python37\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "c:\users\rishu\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rishu\AppData\Local\Programs\Python\Python37\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "c:\users\rishu\appdata\local\programs\python\python37\lib\site-packages\streamlit\__init__.py", line 49, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "c:\users\rishu\appdata\local\programs\python\python37\lib\site-packages\streamlit\proto\RootContainer_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'_

I'm getting this error. can you please help me with it? 
I've installed all the requirements and followed all the steps. I also have anaconda. 

I'm running this command "streamlit run app.py" on powershell.

**Comment by bhattbhavesh91** [comment]
https://stackoverflow.com/questions/61922334/how-to-solve-attributeerror-module-google-protobuf-descriptor-has-no-attribu
